name: "Build & Full test"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cloning the project
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with build script
      run: |
        ./CICD/build.sh
    - name: Send mail on Success
      if: ${{ success() }}    
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: ${{github.repository}} build result - SUCCESS
        # Literal body:
        body: |
          Build job of ${{github.repository}} completed successfully!<br/><br/>

          JOB_CONTEXT: ${{ toJson(job) }}<br/>
          STEPS_CONTEXT: ${{ toJson(steps) }}<br/>
          RUNNER_CONTEXT: ${{ toJson(runner) }}<br/>
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}<br/>
          MATRIX_CONTEXT: ${{ toJson(matrix) }}<br/> 

        to: rsouza01@gmail.com
        from: flask-resplus-api-poc Build
        # Optional content type (defaults to text/plain):
        content_type: text/html

    - name: Send mail on Failure
      if: ${{ failure() }}    
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: ${{github.repository}} build result - Failure
        # Literal body:
        body: |
          Build job of ${{github.repository}} completed with errors!<br/><br/>

          JOB_CONTEXT: ${{ toJson(job) }}<br/>
          STEPS_CONTEXT: ${{ toJson(steps) }}<br/>
          RUNNER_CONTEXT: ${{ toJson(runner) }}<br/>
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}<br/>
          MATRIX_CONTEXT: ${{ toJson(matrix) }}<br/> 

        to: rsouza01@gmail.com
        from: flask-resplus-api-poc
        # Optional content type (defaults to text/plain):
        content_type: text/html
